	CREATE TABLE USERS
   ( USER_ID NUMERIC(10) CONSTRAINT PK_USERS PRIMARY KEY,
     username VARCHAR(20),
     PASSWORD VARCHAR(20),
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20),
    MAIL_ID  VARCHAR(20),
    CONTACT_NO NUMERIC(10),
    ADDRESS VARCHAR(20),
     ROLE    VARCHAR(20)
   );


CREATE TABLE ADMIN
  ( ADMIN_ID NUMERIC(10) CONSTRAINT PK_ADMIN PRIMARY KEY,
            ADMIN_NAME VARCHAR(20)
          
  );


CREATE TABLE AGENT( AGENT_ID NUMERIC(10) CONSTRAINT PK_AGENT PRIMARY KEY,
                   
                    AGENT_NAME VARCHAR(20),
                    DESIGNATION VARCHAR(20),
                    SALARY NUMERIC(10,2) 
                  ); 

CREATE TABLE POLICYHOLDER( POLICY_HOLDER_ID NUMERIC(10) CONSTRAINT PK_POLICYHOLDER PRIMARY KEY,
                       
                            POLICY_HOLDER_NAME VARCHAR(20),
                     
                            CREDIT_CARD VARCHAR(20),
                            DOB DATE,
                            OCCUPATION VARCHAR(20),
                            ANNUAL_INCOME NUMERIC(10,2),
                            IS_RETIRED BOOLEAN,
                            RESIDENCE_TYPE VARCHAR(20),
                            CITY VARCHAR(20),
                            STATE VARCHAR(20),
                            ZIP NUMERIC(10),
                            RESIDENCE_USE VARCHAR(10)
                          );


CREATE TABLE POLICYDETAILS( POLICY_ID NUMERIC(10) CONSTRAINT PK_POLICYDETAILS PRIMARY KEY,
                           
                             POLICY_NAME VARCHAR(20),
                             POLICY_END_DATE DATE,
                             POLICY_EFFECTIVE_DATE DATE,
                             POLICY_TERM NUMERIC(5),
                             POLICY_STATUS VARCHAR(20)
                           );      
      

CREATE TABLE QUOTE( QUOTE_ID NUMERIC(10) CONSTRAINT PK_QUOTE PRIMARY KEY,
                    
                    PREMIUM_TYPE VARCHAR(20),
                    PREMIUM_AMOUNT NUMERIC(10,2),
                    DWELLING_COVERAGE NUMERIC(10,2),
                    DETACHED_STRUCTURE_COVERAGE NUMERIC(10,2),
                    PERSONAL_PROPERTY_COVERAGE NUMERIC(10,2),
                    ADDITIONAL_LIVING_EXPENSE NUMERIC(10,2),
                    MEDICAL_EXPENSE NUMERIC(10,2),
                    DEDUCIBLE_AMOUNT NUMERIC(10,2)
                  );   

CREATE TABLE PROPERTY( PROPERTY_ID NUMERIC(10) CONSTRAINT PK_PROPERTY PRIMARY KEY,
                       
                       MARKET_VALUE NUMERIC(10),
                       YEAR_BUILT NUMERIC(10),
                       SQUARE_FOOTAGE NUMERIC(10),
                       HAS_SWIMMING_POOL BOOLEAN
                     );


CREATE TABLE TRANSACTION( TRANSACTION_ID NUMERIC(10) CONSTRAINT PK_TRANSACTION PRIMARY KEY,
           
                          TRANSACTION_TIME TIME,
                          REGION VARCHAR(20),
                          PAYMENT_TYPE VARCHAR(20)
                        );
ALTER TABLE ADMIN ADD COLUMN USER_ID INT;
ALTER TABLE ADMIN ADD FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE AGENT ADD COLUMN USER_ID INT;
ALTER TABLE AGENT ADD FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE POLICYHOLDER ADD COLUMN USER_ID INT;
ALTER TABLE POLICYHOLDER ADD FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE POLICYHOLDER ADD COLUMN AGENT_ID INT;
ALTER TABLE POLICYHOLDER ADD FOREIGN KEY(AGENT_ID) REFERENCES AGENT(AGENT_ID);

ALTER TABLE POLICYDETAILS ADD COLUMN POLICY_HOLDER_ID INT;
ALTER TABLE POLICYDETAILS ADD FOREIGN KEY(POLICY_HOLDER_ID) REFERENCES POLICYHOLDER(POLICY_HOLDER_ID);

ALTER TABLE QUOTE ADD COLUMN POLICY_HOLDER_ID INT;
ALTER TABLE QUOTE ADD FOREIGN KEY(POLICY_HOLDER_ID) REFERENCES POLICYHOLDER(POLICY_HOLDER_ID);

ALTER TABLE QUOTE ADD COLUMN AGENT_ID INT;
ALTER TABLE QUOTE ADD FOREIGN KEY(AGENT_ID) REFERENCES AGENT(AGENT_ID);

ALTER TABLE PROPERTY ADD COLUMN POLICY_HOLDER_ID INT;
ALTER TABLE PROPERTY ADD FOREIGN KEY(POLICY_HOLDER_ID) REFERENCES POLICYHOLDER(POLICY_HOLDER_ID);

ALTER TABLE TRANSACTION ADD COLUMN QUOTE_ID INT;
ALTER TABLE TRANSACTION ADD FOREIGN KEY(QUOTE_ID) REFERENCES QUOTE(QUOTE_ID);

ALTER TABLE TRANSACTION ADD COLUMN POLICY_ID INT;
ALTER TABLE TRANSACTION ADD FOREIGN KEY(POLICY_ID) REFERENCES POLICYDETAILS(POLICY_ID);

ALTER TABLE AGENT ADD COLUMN ADMIN_ID INT;
ALTER TABLE AGENT ADD FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID);

ALTER TABLE POLICYHOLDER ADD COLUMN ADMIN_ID INT;
ALTER TABLE POLICYHOLDER ADD FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID);

ALTER TABLE POLICYDETAILS ADD COLUMN ADMIN_ID INT;
ALTER TABLE POLICYDETAILS ADD FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID);

ALTER TABLE TRANSACTION ADD COLUMN ADMIN_ID INT;
ALTER TABLE TRANSACTION ADD FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID);